name: "kea"
services:
  dhcp:
    image: "11notes/kea:2.6.1"
    container_name: "kea.dhcp"
    environment:
      TZ: Europe/Zurich
    volumes:
      - "kea-run:/kea/run"
      - "kea-etc:/kea/etc"
    networks:
      dhcp:
        ipv4_address: 192.168.100.67
    restart: always
  ctrl:
    depends_on:
      dhcp:
        condition: service_healthy
        restart: true
    image: "11notes/kea:2.6.1"
    container_name: "kea.ctrl"
    command: ctrl
    environment:
      TZ: Europe/Zurich
    volumes:
      - "kea-run:/kea/run"
    ports:
      - "6780:6780/tcp"
    restart: always
volumes:
  kea-etc:
  kea-run:
networks:
  dhcp:
    driver: macvlan
    driver_opts:
      parent: eth0.100
    ipam:
      config:
        - subnet: 192.168.100.0/24